@echo off


CALL LOG_ENTER pENV

CALL sENV

SET "PROJ_LABEL=%SYS%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%NANO_CONT%"
SET "PROJ_CONT_DATA_DIR=%NANO_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%NANO_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%NANO_CONT_HOME_DIR%"
SET "PROJ_HOST=%NANO_HOST%"
SET "PROJ_HOST_DIR=%NANO_HOST_DIR%"
SET "PROJ_IMG=%NANO_IMG%"
SET "PROJ_PASSWORD=%NANO_PASSWORD%"
SET "PROJ_PORT_EXT=%NANO_PORT_EXT%"
SET "PROJ_PORT_INT=%NANO_PORT_INT%"
SET "PROJ_USER=%NANO_USER%"
SET "PROJ_VOL=%NANO_VOL%"
SET "PROJ_VOL_DIR=%NANO_VOL_DIR%"

CALL LOG_EXIT pENV

