@echo off


CALL LOG_ENTER pENV

call sENV
if exist project\pENV_MOD (
  call project\pENV_MOD
)

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%NANO_CONT%"
SET "PROJ_CONT_DATA_DIR=%NANO_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%NANO_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%NANO_CONT_HOME_DIR%"
SET "PROJ_HOST_DIR=%NANO_HOST_DIR%"
SET "PROJ_IMG=%NANO_IMG%"
SET "PROJ_PORT_INT=%NANO_PORT_INT%"
SET "PROJ_VOL=%NANO_VOL%"
SET "PROJ_VOL_DIR=%NANO_VOL_DIR%"

CALL LOG_EXIT pENV

